-- Schema inicial do Checklist de Inspeção da Frota para Supabase/PostgreSQL.
-- Execute no SQL Editor do projeto. Fotos e assinaturas ficam no Storage;
-- o PostgreSQL guarda somente seus caminhos.

create extension if not exists pgcrypto with schema extensions;

-- Supabase Auth guarda credenciais; esta tabela guarda dados de perfil/permissão.
create table if not exists public.perfis (
  id uuid primary key references auth.users(id) on delete cascade,
  nome_usuario text not null,
  nome_exibicao text not null,
  perfil_acesso text not null default 'motorista'
    check (perfil_acesso in ('administrador','supervisor','operador','motorista','responsavel_manutencao')),
  ativo boolean not null default true,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),
  check (length(btrim(nome_usuario)) > 0),
  check (length(btrim(nome_exibicao)) > 0)
);
create unique index if not exists profiles_username_lower_idx on public.perfis (lower(nome_usuario));

create or replace function public.perfil_atual_usuario()
returns text language sql stable security definer set search_path = '' as $$
  select p.perfil_acesso from public.perfis p
  where p.id = (select auth.uid()) and p.ativo = true limit 1;
$$;

create or replace function public.usuario_eh_admin_ou_supervisor()
returns boolean language sql stable security definer set search_path = '' as $$
  select coalesce(public.perfil_atual_usuario() in ('administrador','supervisor'), false);
$$;

-- No cadastro público, só motorista/operador podem ser escolhidos pelo usuário.
create or replace function public.criar_perfil_novo_usuario()
returns trigger language plpgsql security definer set search_path = '' as $$
declare
  requested_role text;
  requested_username text;
  requested_name text;
begin
  requested_role := lower(coalesce(new.raw_user_meta_data ->> 'role', 'motorista'));
  if requested_role not in ('motorista','operador') then requested_role := 'motorista'; end if;
  requested_username := nullif(btrim(new.raw_user_meta_data ->> 'username'), '');
  requested_name := nullif(btrim(new.raw_user_meta_data ->> 'display_name'), '');
  insert into public.perfis (id, nome_usuario, nome_exibicao, perfil_acesso)
  values (
    new.id,
    coalesce(requested_username, split_part(coalesce(new.email,new.phone,new.id::text), '@', 1)),
    coalesce(requested_name, requested_username, split_part(coalesce(new.email,new.phone,'Usuário'), '@', 1)),
    requested_role
  );
  return new;
end;
$$;
drop trigger if exists on_auth_user_created_profile on auth.users;
create trigger on_auth_user_created_profile after insert on auth.users
for each row execute procedure public.criar_perfil_novo_usuario();

create or replace function public.impedir_alteracao_perfil_nao_autorizada()
returns trigger language plpgsql security definer set search_path = '' as $$
begin
  if (new.perfil_acesso is distinct from old.perfil_acesso or new.ativo is distinct from old.ativo)
     and (select auth.uid()) is not null
     and not public.usuario_eh_admin_ou_supervisor() then
    raise exception 'Somente administrador ou supervisor pode alterar o perfil.';
  end if;
  return new;
end;
$$;
drop trigger if exists profiles_guard_role_change on public.perfis;
create trigger profiles_guard_role_change before update on public.perfis
for each row execute procedure public.impedir_alteracao_perfil_nao_autorizada();

create or replace function public.atualizar_data_modificacao()
returns trigger language plpgsql set search_path = '' as $$
begin
  new.atualizado_em := now();
  return new;
end;
$$;
drop trigger if exists profiles_touch_updated_at on public.perfis;
create trigger profiles_touch_updated_at before update on public.perfis
for each row execute procedure public.atualizar_data_modificacao();

create table if not exists public.veiculos (
  id uuid primary key default gen_random_uuid(),
  identificacao text not null unique,
  ativo boolean not null default true,
  criado_por uuid references public.perfis(id) on delete set null,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),
  check (length(btrim(identificacao)) > 0)
);
drop trigger if exists vehicles_touch_updated_at on public.veiculos;
create trigger vehicles_touch_updated_at before update on public.veiculos
for each row execute procedure public.atualizar_data_modificacao();

create table if not exists public.definicoes_checklist (
  id smallint generated by default as identity primary key,
  chave_item text not null unique,
  rotulo text not null,
  categoria text not null,
  ordem_exibicao smallint not null unique,
  ativo boolean not null default true
);
insert into public.definicoes_checklist (chave_item,rotulo,categoria,ordem_exibicao) values
 ('oil','Nível de óleo do motor','Motor e fluidos',1),
 ('coolant','Nível do líquido de arrefecimento','Motor e fluidos',2),
 ('fuel','Nível de combustível','Motor e fluidos',3),
 ('leaks','Vazamentos de óleo, água ou combustível','Motor e fluidos',4),
 ('battery','Bateria e conexões','Motor e fluidos',5),
 ('tires','Condição dos pneus','Pneus, freios e direção',6),
 ('tirePressure','Pressão dos pneus','Pneus, freios e direção',7),
 ('brakes','Sistema de freios','Pneus, freios e direção',8),
 ('suspension','Sistema de direção e suspensão','Pneus, freios e direção',9),
 ('lights','Faróis, lanternas e indicadores','Segurança e iluminação',10),
 ('signals','Seta e buzina','Segurança e iluminação',11),
 ('mirrors','Espelhos retrovisores e visibilidade','Segurança e iluminação',12),
 ('safety','Cinto de segurança e equipamentos de proteção','Segurança e iluminação',13),
 ('body','Estado visual da cabine e carroceria','Cabine e estrutura',14),
 ('doors','Portas, travas e fechaduras','Cabine e estrutura',15),
 ('windows','Vidros e limpa-vidros','Cabine e estrutura',16),
 ('documents','Documentação do veículo e habilitação','Cabine e estrutura',17)
on conflict (chave_item) do update set rotulo=excluded.rotulo, categoria=excluded.categoria, ordem_exibicao=excluded.ordem_exibicao;

create table if not exists public.inspecoes (
  id uuid primary key default gen_random_uuid(),
  veiculo_id uuid not null references public.veiculos(id) on delete restrict,
  inspecionado_por uuid not null references public.perfis(id) on delete restrict,
  nome_operador_registrado text not null,
  responsavel_manutencao_id uuid references public.perfis(id) on delete set null,
  nome_responsavel_manutencao text,
  inspecionado_em timestamptz not null,
  leitura_medidor numeric(12,2) not null check (leitura_medidor >= 0),
  tipo_medidor text not null check (tipo_medidor in ('hodometro','horimetro')),
  local_inspecao text not null,
  observacoes text,
  severidade text not null default 'baixa' check (severidade in ('baixa','media','alta','critica')),
  caminho_assinatura text,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),
  check (length(btrim(nome_operador_registrado)) > 0),
  check (length(btrim(local_inspecao)) > 0)
);
drop trigger if exists inspections_touch_updated_at on public.inspecoes;
create trigger inspections_touch_updated_at before update on public.inspecoes
for each row execute procedure public.atualizar_data_modificacao();

create table if not exists public.resultados_checklist (
  inspecao_id uuid not null references public.inspecoes(id) on delete cascade,
  definicao_checklist_id smallint not null references public.definicoes_checklist(id) on delete restrict,
  rotulo_item_registrado text not null,
  situacao text not null check (situacao in ('ok','nao_ok','na')),
  observacoes_item text,
  primary key (inspecao_id, definicao_checklist_id)
);

create table if not exists public.fotos_inspecao (
  id uuid primary key default gen_random_uuid(),
  inspecao_id uuid not null references public.inspecoes(id) on delete cascade,
  caminho_arquivo text not null unique,
  nome_arquivo_original text not null,
  tipo_conteudo text not null,
  tamanho_bytes bigint check (tamanho_bytes is null or tamanho_bytes >= 0),
  enviado_por uuid not null references public.perfis(id) on delete restrict,
  criado_em timestamptz not null default now()
);

create table if not exists public.solicitacoes_manutencao (
  id uuid primary key default gen_random_uuid(),
  inspecao_id uuid not null references public.inspecoes(id) on delete restrict,
  veiculo_id uuid not null references public.veiculos(id) on delete restrict,
  aberto_por uuid not null references public.perfis(id) on delete restrict,
  atribuido_a uuid references public.perfis(id) on delete set null,
  descricao text not null,
  severidade text not null default 'baixa' check (severidade in ('baixa','media','alta','critica')),
  situacao text not null default 'aberta' check (situacao in ('aberta','em_manutencao','concluida')),
  servico_realizado text,
  observacoes_solucao text,
  aberto_em timestamptz not null default now(),
  iniciado_em timestamptz,
  concluido_em timestamptz,
  atualizado_em timestamptz not null default now(),
  check (length(btrim(descricao)) > 0),
  check ((situacao = 'concluida' and concluido_em is not null) or (situacao <> 'concluida' and concluido_em is null))
);
drop trigger if exists maintenance_requests_touch_updated_at on public.solicitacoes_manutencao;
create trigger maintenance_requests_touch_updated_at before update on public.solicitacoes_manutencao
for each row execute procedure public.atualizar_data_modificacao();

create table if not exists public.historico_status_manutencao (
  id bigint generated always as identity primary key,
  solicitacao_manutencao_id uuid not null references public.solicitacoes_manutencao(id) on delete cascade,
  situacao_anterior text,
  situacao_nova text not null check (situacao_nova in ('aberta','em_manutencao','concluida')),
  alterado_por uuid references public.perfis(id) on delete set null,
  observacao_alteracao text,
  alterado_em timestamptz not null default now()
);
create or replace function public.registrar_alteracao_status_manutencao()
returns trigger language plpgsql security definer set search_path = '' as $$
begin
  if tg_op = 'INSERT' then
    insert into public.historico_status_manutencao(solicitacao_manutencao_id,situacao_anterior,situacao_nova,alterado_por)
    values (new.id,null,new.situacao,(select auth.uid()));
  elsif new.situacao is distinct from old.situacao then
    insert into public.historico_status_manutencao(solicitacao_manutencao_id,situacao_anterior,situacao_nova,alterado_por)
    values (new.id,old.situacao,new.situacao,(select auth.uid()));
  end if;
  return new;
end;
$$;
drop trigger if exists maintenance_status_history_trigger on public.solicitacoes_manutencao;
create trigger maintenance_status_history_trigger after insert or update of situacao
on public.solicitacoes_manutencao for each row execute procedure public.registrar_alteracao_status_manutencao();

create index if not exists inspections_vehicle_date_idx on public.inspecoes(veiculo_id,inspecionado_em desc);
create index if not exists inspections_actor_date_idx on public.inspecoes(inspecionado_por,inspecionado_em desc);
create index if not exists maintenance_status_opened_idx on public.solicitacoes_manutencao(situacao,aberto_em desc);
create index if not exists maintenance_assignee_status_idx on public.solicitacoes_manutencao(atribuido_a,situacao);
create index if not exists photos_inspection_idx on public.fotos_inspecao(inspecao_id);
create index if not exists maintenance_history_request_date_idx on public.historico_status_manutencao(solicitacao_manutencao_id,alterado_em desc);

-- RLS: as políticas controlam quais linhas os clientes autenticados podem acessar.
alter table public.perfis enable row level security;
alter table public.veiculos enable row level security;
alter table public.definicoes_checklist enable row level security;
alter table public.inspecoes enable row level security;
alter table public.resultados_checklist enable row level security;
alter table public.fotos_inspecao enable row level security;
alter table public.solicitacoes_manutencao enable row level security;
alter table public.historico_status_manutencao enable row level security;

revoke all on public.perfis, public.veiculos, public.definicoes_checklist, public.inspecoes,
  public.resultados_checklist, public.fotos_inspecao, public.solicitacoes_manutencao,
  public.historico_status_manutencao from anon, authenticated;
grant select, update on public.perfis to authenticated;
grant select, insert, update on public.veiculos to authenticated;
grant select on public.definicoes_checklist to authenticated;
grant select, insert, update, delete on public.inspecoes to authenticated;
grant select, insert, update, delete on public.resultados_checklist to authenticated;
grant select, insert, delete on public.fotos_inspecao to authenticated;
grant select, insert, update on public.solicitacoes_manutencao to authenticated;
grant select on public.historico_status_manutencao to authenticated;

drop policy if exists profiles_read_self_or_manager on public.perfis;
create policy profiles_read_self_or_manager on public.perfis for select to authenticated
using (id=(select auth.uid()) or (select public.usuario_eh_admin_ou_supervisor()));
drop policy if exists profiles_update_self_or_manager on public.perfis;
create policy profiles_update_self_or_manager on public.perfis for update to authenticated
using (id=(select auth.uid()) or (select public.usuario_eh_admin_ou_supervisor()))
with check (id=(select auth.uid()) or (select public.usuario_eh_admin_ou_supervisor()));

drop policy if exists vehicles_read_authenticated on public.veiculos;
create policy vehicles_read_authenticated on public.veiculos for select to authenticated
using ((select public.perfil_atual_usuario()) is not null and ativo=true);
drop policy if exists vehicles_manage_admin_supervisor on public.veiculos;
create policy vehicles_manage_admin_supervisor on public.veiculos for all to authenticated
using ((select public.usuario_eh_admin_ou_supervisor())) with check ((select public.usuario_eh_admin_ou_supervisor()));
drop policy if exists checklist_definitions_read_authenticated on public.definicoes_checklist;
create policy checklist_definitions_read_authenticated on public.definicoes_checklist
for select to authenticated using ((select public.perfil_atual_usuario()) is not null and ativo=true);

drop policy if exists inspections_read_authenticated on public.inspecoes;
create policy inspections_read_authenticated on public.inspecoes for select to authenticated
using (inspecionado_por=(select auth.uid()) or (select public.usuario_eh_admin_ou_supervisor()));
drop policy if exists inspections_insert_self on public.inspecoes;
create policy inspections_insert_self on public.inspecoes for insert to authenticated
with check (inspecionado_por=(select auth.uid()) and (select public.perfil_atual_usuario()) is not null);
drop policy if exists inspections_update_managers on public.inspecoes;
create policy inspections_update_managers on public.inspecoes for update to authenticated
using ((select public.usuario_eh_admin_ou_supervisor())) with check ((select public.usuario_eh_admin_ou_supervisor()));
drop policy if exists inspections_delete_admin on public.inspecoes;
create policy inspections_delete_admin on public.inspecoes for delete to authenticated
using ((select public.perfil_atual_usuario())='administrador');

drop policy if exists checklist_results_read_authenticated on public.resultados_checklist;
create policy checklist_results_read_authenticated on public.resultados_checklist
for select to authenticated using (exists (
  select 1 from public.inspecoes i where i.id=inspecao_id
    and (i.inspecionado_por=(select auth.uid()) or (select public.usuario_eh_admin_ou_supervisor()))
));
drop policy if exists checklist_results_insert_own_inspection on public.resultados_checklist;
create policy checklist_results_insert_own_inspection on public.resultados_checklist
for insert to authenticated with check (exists (
  select 1 from public.inspecoes i where i.id=inspecao_id and i.inspecionado_por=(select auth.uid())
));
drop policy if exists checklist_results_update_managers on public.resultados_checklist;
create policy checklist_results_update_managers on public.resultados_checklist for update to authenticated
using ((select public.usuario_eh_admin_ou_supervisor())) with check ((select public.usuario_eh_admin_ou_supervisor()));
drop policy if exists checklist_results_delete_managers on public.resultados_checklist;
create policy checklist_results_delete_managers on public.resultados_checklist for delete to authenticated
using ((select public.usuario_eh_admin_ou_supervisor()));

drop policy if exists inspection_photos_read_authenticated on public.fotos_inspecao;
create policy inspection_photos_read_authenticated on public.fotos_inspecao
for select to authenticated using (exists (
  select 1 from public.inspecoes i where i.id=inspecao_id
    and (i.inspecionado_por=(select auth.uid()) or (select public.usuario_eh_admin_ou_supervisor()))
));
drop policy if exists inspection_photos_insert_own_inspection on public.fotos_inspecao;
create policy inspection_photos_insert_own_inspection on public.fotos_inspecao
for insert to authenticated with check (
  enviado_por=(select auth.uid()) and exists (
    select 1 from public.inspecoes i where i.id=inspecao_id and i.inspecionado_por=(select auth.uid())
  )
);
drop policy if exists inspection_photos_delete_own_or_manager on public.fotos_inspecao;
create policy inspection_photos_delete_own_or_manager on public.fotos_inspecao for delete to authenticated
using (enviado_por=(select auth.uid()) or (select public.usuario_eh_admin_ou_supervisor()));

drop policy if exists maintenance_requests_read_authenticated on public.solicitacoes_manutencao;
create policy maintenance_requests_read_authenticated on public.solicitacoes_manutencao
for select to authenticated using (
  aberto_por=(select auth.uid()) or atribuido_a=(select auth.uid())
  or (select public.usuario_eh_admin_ou_supervisor())
);
drop policy if exists maintenance_requests_insert_own_inspection on public.solicitacoes_manutencao;
create policy maintenance_requests_insert_own_inspection on public.solicitacoes_manutencao
for insert to authenticated with check (
  aberto_por=(select auth.uid()) and exists (
    select 1 from public.inspecoes i
    where i.id=solicitacoes_manutencao.inspecao_id
      and i.veiculo_id=solicitacoes_manutencao.veiculo_id
      and i.inspecionado_por=(select auth.uid())
  )
);
drop policy if exists maintenance_requests_update_assignee_or_manager on public.solicitacoes_manutencao;
create policy maintenance_requests_update_assignee_or_manager on public.solicitacoes_manutencao for update to authenticated
using (atribuido_a=(select auth.uid()) or (select public.usuario_eh_admin_ou_supervisor()))
with check (atribuido_a=(select auth.uid()) or (select public.usuario_eh_admin_ou_supervisor()));

drop policy if exists maintenance_history_read_authenticated on public.historico_status_manutencao;
create policy maintenance_history_read_authenticated on public.historico_status_manutencao
for select to authenticated using (
  exists (select 1 from public.solicitacoes_manutencao m
    where m.id=solicitacao_manutencao_id
      and (m.aberto_por=(select auth.uid()) or m.atribuido_a=(select auth.uid())
        or (select public.usuario_eh_admin_ou_supervisor())))
);

-- Bucket privado. Grave os objetos como <auth.uid>/<inspecao_id>/<arquivo>.
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values ('inspection-evidence','inspection-evidence',false,10485760,array['image/jpeg','image/png','image/webp'])
on conflict (id) do update set public=false,file_size_limit=excluded.file_size_limit,
  allowed_mime_types=excluded.allowed_mime_types;
drop policy if exists inspection_evidence_read_authenticated on storage.objects;
create policy inspection_evidence_read_authenticated on storage.objects for select to authenticated
using (bucket_id='inspection-evidence' and (
  (storage.foldername(name))[1]=(select auth.uid())::text
  or (select public.usuario_eh_admin_ou_supervisor())
));
drop policy if exists inspection_evidence_upload_own_folder on storage.objects;
create policy inspection_evidence_upload_own_folder on storage.objects for insert to authenticated
with check (bucket_id='inspection-evidence' and (storage.foldername(name))[1]=(select auth.uid())::text);
drop policy if exists inspection_evidence_delete_own_folder on storage.objects;
create policy inspection_evidence_delete_own_folder on storage.objects for delete to authenticated
using (bucket_id='inspection-evidence' and (
  (storage.foldername(name))[1]=(select auth.uid())::text or (select public.usuario_eh_admin_ou_supervisor())
));
